version: "3.7"
services:
  postgres:
    container_name: 'to-do-postgres'
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=db_user'
      - 'POSTGRES_DB=todo_db'
      - 'POSTGRES_PASSWORD=password'